name: Python application test with Github Actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up Pythong 3.10.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13
      - name: Install packages
        run: make install
      - name: Lint with pylint
        run: make lint
      - name: Test with pytest
        run: make test
      - name: Format with Python Black
        run: make format
